Type: AWS::DynamoDB::Table
Properties:
  TableName: ${self:custom.DynamoDb.AuctionsTable.name}
  BillingMode: PAY_PER_REQUEST
  AttributeDefinitions:
    - AttributeName: id
      AttributeType: S
    - AttributeName: status
      AttributeType: S
    - AttributeName: endingAt
      AttributeType: S
  KeySchema:
    - AttributeName: id
      KeyType: HASH # this shows that id is the partition key of this table
  GlobalSecondaryIndexes: # we can
    - IndexName: statusAndEndDate
      KeySchema:
        - AttributeName: status
          KeyType: HASH
        - AttributeName: endingAt
          KeyType: RANGE
      Projection:
        ProjectionType: ALL
